name: Karate Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno (dev, staging, prod)'
        required: true
        default: 'dev'
      tags:
        description: 'Tags (ej: @smoke,@regression)'
        required: true
        default: '@smoke'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run Karate Tests
      run: mvn test "-Dkarate.env=${{ github.event.inputs.environment }}" "-Dkarate.options=--tags ${{ github.event.inputs.tags }}"

    - name: Prepare Reports
      run: mkdir -p reports && cp -r target/karate-reports/* reports/ && cp -r target/cucumber-html-reports/* reports/

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: reports
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
    uses: actions/deploy-pages@v2